In [15]:
import numpy as np
import os


Path = "/home/ug-ml/felix-ML/TrainingDataRaw/1001to2000/1650/LaCu3Pt37O12_Sim_0050A_128x128"

NewPath = "/home/ug-ml/felix-ML/DataGenerator2/Data/training/0"
NewPath_i = "/Crystal_1650.npy"


def ThicknessString(String): #Takes the file name string, looks at the thickness part and returns a integer corresponding to the thickness class
    if(String == "0050"):
        return 0
    elif(String == "0250"):
        return 1
    elif(String == "0450"):
        return 2
    elif(String == "0650"):
        return 3
    elif(String == "0850"):
        return 4
    elif(String == "1050"):
        return 5
    elif(String == "1250"):
        return 6
    elif(String == "1450"):
        return 7
    elif(String == "1650"):
        return 8
    elif(String == "1850"):
        return 9
    else: #If something goes wrong, an error will be printed
        print("ERROR")
        return 10

    
def Position():
    IndexArray = np.zeros(8 * 8, dtype = int).reshape(8, 8) #Declare Image array
    index = 0
    for i in range(0, 8):
        for j in range(0, 8):
            if(i >= j):
                IndexArray[i][j] = index
                index+=1
    return IndexArray

DirectionIndex = Position()






In [17]:
FolderPath = sorted(os.listdir(Path))

OldArray = np.zeros(36 * 128 * 128, dtype = np.float32).reshape(36, 128, 128)

for i in FolderPath:
    if(i[-4:] == ".bin"):
        #print(i)
        DirectionName = list(map(int, i.split("_")[-1].split(".")[0].split("+")[1:]))
        if(DirectionName[0] <= 14 and DirectionName[1] <=14):
            Directon_i = DirectionIndex[int(DirectionName[0]/2)][int(DirectionName[1]/2)]
            data = np.fromfile(Path + "/" + i, dtype=np.float64).reshape(128, 128)
            OldArray[Directon_i] = data

    elif(i[-4:] == ".cif" or i[-4:] == ".gif" or i[-4:] == ".txt"):
        #Ignore
        m = 2
    else:
        print("File or folder with name (Warning2):", l)

    
NewArray = np.load(NewPath+NewPath_i)
print(OldArray.shape)
print(NewArray.shape)

Diffrence = NewArray - OldArray
for i in NewArray:
    print(i)

#Original = np.load(Path+"/Cu2Br8WBr6_0050_+0+0+0.npy")
#

#print(Original)
#print(New[0])


(36, 128, 128)
(36, 128, 128)
[[0.5918366  0.5926774  0.5924532  ... 0.5925062  0.5927318  0.59188986]
 [0.5926675  0.5920241  0.59314626 ... 0.59925497 0.59869933 0.5982399 ]
 [0.59866214 0.5992037  0.59976035 ... 0.59980017 0.5992435  0.598702  ]
 ...
 [0.598702   0.5992436  0.59980017 ... 0.599761   0.59920436 0.59866273]
 [0.5982399  0.59869933 0.59925497 ... 0.599216   0.59866023 0.59820074]
 [0.5977909  0.59824646 0.5987197  ... 0.59868085 0.5982075  0.5977519 ]]
[[0.00398264 0.00387832 0.00384592 ... 0.00474201 0.00470428 0.00464382]
 [0.00386405 0.00386557 0.00373906 ... 0.00474016 0.00471364 0.00468346]
 [0.00324509 0.00316997 0.00309409 ... 0.0047282  0.00470433 0.00467571]
 ...
 [0.00324277 0.00316769 0.00309185 ... 0.00472927 0.00470542 0.00467682]
 [0.00333451 0.00325761 0.00318433 ... 0.00474123 0.00471472 0.00468456]
 [0.00342431 0.00335119 0.00327615 ... 0.00475073 0.00472261 0.00468844]]
[[0.01928678 0.01882445 0.01874121 ... 0.03931201 0.03945028 0.03965793]
 [0.01883